export default function getLeaderboardData() {
    return [
        {
            id: 1,
            name: "Sunflower",
            author: "James McA",
            firstName: "James",
            lastName: "McAllen",
        },
        {
            id: 2,
            name: "Twins",
            author: "James McA",
            firstName: "James",
            lastName: "McAllen",
            profileImageUrl: "/avatar_1.png",
            artwork_price: 0.25,
            artwork_unit: "ETH",
        },
        {
            id: 3,
            name: "Hope",
            author: "James McA",
            firstName: "James",
            lastName: "McAllen",
            profileImageUrl: "/avatar_2.jpeg",
            artwork_price: 0.15,
            artwork_unit: "ETH",
        },
        {
            id: 4,
            name: "Warrior",
            description:" AI generated Gundam suit",
            author: "James McA",
            firstName: "James",
            lastName: "McAllen",
            profileImageUrl: "/avatar_3.jpeg",
        },
        {
            id: 5,
            name: "Screaming Shiba",
            author: "Vincent Chen",
            firstName: "Vincent",
            lastName: "Chen",
            profileImageUrl: "/avatar_4.jpeg",
        },
        {
            id: 6,
            name: "Heaven",
            author: "Sunayyah",
            firstName: "Sunay",
            lastName: "Yah",
            profileImageUrl: "/avatar_5.jpeg",
            artwork_price: 0.5,
            artwork_unit: "ETH",
        },
        {
            id: 7,
            name: "Screaming Shiba",
            author: "Haper",
            firstName: "Ha",
            lastName: "Per",
            profileImageUrl: "/avatar_6.jpeg",
            artwork_price: 1.5,
            artwork_unit: "ETH",
        },
        {
            id: 8,
            name: "Warrior",
            author: "Haper",
            firstName: "Ha",
            lastName: "Per",
            profileImageUrl: "/avatar_6.jpeg",
            artwork_price: 2.5,
            artwork_unit: "ETH",
        },
        {
            id: 9,
            name: "Down in my heart",
            author: "Haper",
            firstName: "Ha",
            lastName: "Per",
            profileImageUrl: "/avatar_6.jpeg",
            artwork_price: 0.25,
            artwork_unit: "ETH",
        },
        {
            id: 10,
            name: "Future cars",
            author: "Haper",
            firstName: "Ha",
            lastName: "Per",
            profileImageUrl: "/avatar_6.jpeg",
            artwork_price: 0.5,
            artwork_unit: "ETH",
        },
    ];
}