import './globals.css'
import { Inter } from 'next/font/google'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

import NavBar from '../components/navBar';
import { FormProvider } from '../context/formContext';
import { NotificationContextProvider } from '../context/notificationContext';
import AuthProvider from '../context/authContext';
import Notification from '../components/notification';
import { FormDataContextProvider } from '../context/formDataContext';

const inter = Inter({ 
    weight: '400',
    subsets: ['latin'],
    display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children
}: {
  children: React.ReactElement
}) {
  return (
    <html lang="en">
        <AuthProvider>
            <body className={inter.className}>
                <NavBar />
                <NotificationContextProvider>
                    <FormDataContextProvider>
                        {children}
                    </FormDataContextProvider>
                    <Notification /> 
                </NotificationContextProvider>
            </body>  
        </AuthProvider>
    </html>
  )
}
